<?php

namespace Database\Seeders\Provisionada;

use Illuminate\Database\Seeder;

class ExogenaFormatosProvisionalSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('exogena_formatos')->truncate();

        \DB::table('exogena_formatos')->insert([
            [
                'id' => 1,
                'formato' => '1001',
                'tipo_documento' => 1,
                'digito_verificacion' => 0,
                'numero_documento' => 1,
                'primer_apellido' => 1,
                'segundo_apellido' => 1,
                'primer_nombre' => 1,
                'otros_nombres' => 1,
                'razon_social' => 1,
                'direccion' => 1,
                'departamento' => 1,
                'municipio' => 1,
                'pais' => 1,
            ],
            [
                'id' => 2,
                'formato' => '1003',
                'tipo_documento' => 1,
                'digito_verificacion' => 1,
                'numero_documento' => 1,
                'primer_apellido' => 1,
                'segundo_apellido' => 1,
                'primer_nombre' => 1,
                'otros_nombres' => 1,
                'razon_social' => 1,
                'direccion' => 1,
                'departamento' => 1,
                'municipio' => 1,
                'pais' => 1,
            ],
            [
                'id' => 3,
                'formato' => '1005',
                'tipo_documento' => 1,
                'digito_verificacion' => 1,
                'numero_documento' => 1,
                'primer_apellido' => 1,
                'segundo_apellido' => 1,
                'primer_nombre' => 1,
                'otros_nombres' => 1,
                'razon_social' => 1,
                'direccion' => 0,
                'departamento' => 0,
                'municipio' => 0,
                'pais' => 0,
            ],
            [
                'id' => 4,
                'formato' => '1006',
                'tipo_documento' => 1,
                'digito_verificacion' => 1,
                'numero_documento' => 1,
                'primer_apellido' => 1,
                'segundo_apellido' => 1,
                'primer_nombre' => 1,
                'otros_nombres' => 1,
                'razon_social' => 1,
                'direccion' => 0,
                'departamento' => 0,
                'municipio' => 0,
                'pais' => 0,
            ],
            [
                'id' => 5,
                'formato' => '1007',
                'tipo_documento' => 1,
                'digito_verificacion' => 1,
                'numero_documento' => 1,
                'primer_apellido' => 1,
                'segundo_apellido' => 1,
                'primer_nombre' => 1,
                'otros_nombres' => 1,
                'razon_social' => 1,
                'direccion' => 0,
                'departamento' => 0,
                'municipio' => 0,
                'pais' => 1,
            ],
            [
                'id' => 6,
                'formato' => '1008',
                'tipo_documento' => 1,
                'digito_verificacion' => 1,
                'numero_documento' => 1,
                'primer_apellido' => 1,
                'segundo_apellido' => 1,
                'primer_nombre' => 1,
                'otros_nombres' => 1,
                'razon_social' => 1,
                'direccion' => 1,
                'departamento' => 1,
                'municipio' => 1,
                'pais' => 1,
            ],
            [
                'id' => 7,
                'formato' => '1009',
                'tipo_documento' => 1,
                'digito_verificacion' => 1,
                'numero_documento' => 1,
                'primer_apellido' => 1,
                'segundo_apellido' => 1,
                'primer_nombre' => 1,
                'otros_nombres' => 1,
                'razon_social' => 1,
                'direccion' => 1,
                'departamento' => 1,
                'municipio' => 1,
                'pais' => 1,
            ],
            [
                'id' => 8,
                'formato' => '1011',
                'tipo_documento' => 0,
                'digito_verificacion' => 0,
                'numero_documento' => 0,
                'primer_apellido' => 0,
                'segundo_apellido' => 0,
                'primer_nombre' => 0,
                'otros_nombres' => 0,
                'razon_social' => 0,
                'direccion' => 0,
                'departamento' => 0,
                'municipio' => 0,
                'pais' => 0,
            ],
            [
                'id' => 9,
                'formato' => '1012',
                'tipo_documento' => 1,
                'digito_verificacion' => 1,
                'numero_documento' => 1,
                'primer_apellido' => 1,
                'segundo_apellido' => 1,
                'primer_nombre' => 1,
                'otros_nombres' => 1,
                'razon_social' => 1,
                'direccion' => 0,
                'departamento' => 0,
                'municipio' => 0,
                'pais' => 1,
            ],
            [
                'id' => 10,
                'formato' => '2276',
                'tipo_documento' => 1,
                'digito_verificacion' => 1,
                'numero_documento' => 1,
                'primer_apellido' => 1,
                'segundo_apellido' => 1,
                'primer_nombre' => 1,
                'otros_nombres' => 1,
                'razon_social' => 0,
                'direccion' => 1,
                'departamento' => 1,
                'municipio' => 1,
                'pais' => 1,
            ],
        ]);


    }
}