<?php

namespace Database\Seeders\Provisionada;

use Illuminate\Database\Seeder;

class ExogenaFormatoColumnasProvisionalSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('exogena_formato_columnas')->truncate();

        \DB::table('exogena_formato_columnas')->insert([
            [
                'id' => 1,
                'id_exogena_formato' => 1,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'pago_cuenta_deducible',
                'nombre' => 'Pago Cuenta Deducible',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 2,
                'id_exogena_formato' => 1,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'pago_cuenta_no_deducible',
                'nombre' => 'Pago Cuenta No Deducible',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 3,
                'id_exogena_formato' => 1,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'iva_mayor_deducible',
                'nombre' => 'IVA Mayor Deducible',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 4,
                'id_exogena_formato' => 1,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'iva_mayor_no_deducible',
                'nombre' => 'IVA Mayor No Deducible',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 5,
                'id_exogena_formato' => 1,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'retencion_practicada_renta',
                'nombre' => 'Retención Practicada Renta',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 6,
                'id_exogena_formato' => 1,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'retencion_asumida_renta',
                'nombre' => 'Retención Asumida Renta',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 7,
                'id_exogena_formato' => 1,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'retencion_iva_practicado_comun',
                'nombre' => 'Retención IVA Practicado Común',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 8,
                'id_exogena_formato' => 1,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'retencion_practicada_iva_no_domiciliado',
                'nombre' => 'Retención Practicada IVA No Domiciliado',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 9,
                'id_exogena_formato' => 3,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'impuesto_descontable',
                'nombre' => 'Impuesto descontable',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 10,
                'id_exogena_formato' => 3,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'iva_descontable_por_devoluciones_en_ventas',
                'nombre' => 'IVA descontable por devoluciones en ventas',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 11,
                'id_exogena_formato' => 4,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'impuesto_generado',
                'nombre' => 'Impuesto generado',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 12,
                'id_exogena_formato' => 4,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'iva_generado_por_devoluciones_en_compras',
                'nombre' => 'IVA generado por devoluciones en compras',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 13,
                'id_exogena_formato' => 4,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'impuesto_al_consumo',
                'nombre' => 'Impuesto al consumo',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 14,
                'id_exogena_formato' => 5,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'ingresos_brutos_recibidos',
                'nombre' => 'Ingresos brutos recibidos',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 15,
                'id_exogena_formato' => 5,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'devoluciones_rebajas_y_descuentos',
                'nombre' => 'Devoluciones, rebajas y descuentos',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 16,
                'id_exogena_formato' => 10,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'pagos_por_salario',
                'nombre' => 'Pagos por salario',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 17,
                'id_exogena_formato' => 10,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'pagos_por_emolumentos_eclesiasticos',
                'nombre' => 'Pagos por emolumentos eclesiásticos',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 18,
                'id_exogena_formato' => 10,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'pagos_por_honorarios',
                'nombre' => 'Pagos por honorarios',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 19,
                'id_exogena_formato' => 10,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'pagos_por_servicios',
                'nombre' => 'Pagos por servicios',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 20,
                'id_exogena_formato' => 10,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'pagos_por_comisiones',
                'nombre' => 'Pagos por comisiones',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 21,
                'id_exogena_formato' => 10,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'pagos_por_prestaciones_sociales',
                'nombre' => 'Pagos por prestaciones sociales',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 22,
                'id_exogena_formato' => 10,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'pagos_por_viaticos',
                'nombre' => 'Pagos por viáticos',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 23,
                'id_exogena_formato' => 10,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'pagos_por_gastos_de_representacion',
                'nombre' => 'Pagos por gastos de representación',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 24,
                'id_exogena_formato' => 10,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'pagos_por_compensaciones',
                'nombre' => 'Pagos por compensaciones trabajo asociado cooperativo',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 25,
                'id_exogena_formato' => 10,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'otros_pagos',
                'nombre' => 'Otros pagos',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 26,
                'id_exogena_formato' => 10,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'pagos_realizados_con_bonos_electronicos',
                'nombre' => 'Pagos realizados con bonos electrónicos o de papel de servicio, cheques, tarjetas, vales, etc.',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 27,
                'id_exogena_formato' => 10,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'cesantias_e_intereses_de_cesantias',
                'nombre' => 'Cesantías e intereses de cesantías efectivamente pagadas, consignadas o reconocidas en el periodo',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 28,
                'id_exogena_formato' => 10,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'pensiones_de_jubilacion_vejez_o_invalidez',
                'nombre' => 'Pensiones de Jubilación, vejez o invalidez',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 29,
                'id_exogena_formato' => 10,
                'id_tipo_concepto_nomina' => 'salud',
                'id_columna_porcentaje_base' => null,
                'columna' => 'aportes_obligatorios_por_salud',
                'nombre' => 'Aportes Obligatorios por Salud',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 30,
                'id_exogena_formato' => 10,
                'id_tipo_concepto_nomina' => 'fondo_pension',
                'id_columna_porcentaje_base' => null,
                'columna' => 'aportes_obligatorios_a_fondos_de_pensiones',
                'nombre' => 'Aportes obligatorios a fondos de pensiones y solidaridad pensional y Aportes voluntarios al - RAIS',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 31,
                'id_exogena_formato' => 10,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'aportes_voluntarios_a_fondos_de_pensiones_voluntarias',
                'nombre' => 'Aportes voluntarios a fondos de pensiones voluntarias',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 32,
                'id_exogena_formato' => 10,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'aportes_a_cuentas_afc',
                'nombre' => 'Aportes a cuentas AFC',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 33,
                'id_exogena_formato' => 10,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'valor_de_las_retenciones_en_la_fuente',
                'nombre' => 'Valor de las retenciones en la fuente por pagos de rentas de trabajo o pensiones',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 34,
                'id_exogena_formato' => 2,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => 35,
                'columna' => 'valor_acumulado_del_pago',
                'nombre' => 'Valor acumulado del pago o abono sujeto a retención en la fuente',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 35,
                'id_exogena_formato' => 2,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'retencion_en_la_fuente_que_le_practicaron',
                'nombre' => 'Retención en la fuente que le practicaron',
                'acumulado' => 0,
                'saldo' => 1,
            ],
            [
                'id' => 36,
                'id_exogena_formato' => 6,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'saldo_cuentas_por_cobrar',
                'nombre' => 'Saldo cuentas por cobrar',
                'acumulado' => 1,
                'saldo' => 1,
            ],
            [
                'id' => 37,
                'id_exogena_formato' => 7,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'saldo_cuentas_por_pagar',
                'nombre' => 'Saldo cuentas por pagar',
                'acumulado' => 1,
                'saldo' => 1,
            ],
            [
                'id' => 38,
                'id_exogena_formato' => 8,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'saldo',
                'nombre' => 'Saldo',
                'acumulado' => 0,
                'saldo' => 0,
            ],
            [
                'id' => 39,
                'id_exogena_formato' => 9,
                'id_tipo_concepto_nomina' => null,
                'id_columna_porcentaje_base' => null,
                'columna' => 'valor',
                'nombre' => 'Valor',
                'acumulado' => 1,
                'saldo' => 1,
            ]
        ]);


    }
}